---
language: ruby
sudo: false
rvm:
  - 2.1
  - 2.0
  - 2.2.5
  - 2.3.1
branches:
  only: [master]
env:
  - COMMAND=rake
matrix:
  allow_failures:
    env: COMMAND='rubocop --list-target-files'
  include:
    - rvm: 2.3.1
      env: COMMAND=rubocop
script:
  - bundle exec $COMMAND
cache: bundler
