---
language: ruby
sudo: false
rvm:
  - 2.1
  - 2.0
  - 2.2.6
  - 2.3.3
branches:
  only: [master]
env:
  - COMMAND=rake
matrix:
  include:
    - rvm: 2.3.3
      env: COMMAND=rubocop
script:
  - bundle exec $COMMAND
cache: bundler
